[profile.default]
src = 'src'
out = 'out'
libs = ['lib']

# Extreme Fuzzing CI Profile :P
[profile.ci]
# 100_000
fuzz_runs = 100_000

# RPC Endpoints
[rpc_endpoints]
celo = "https://celo-alfajores.infura.io/v3/dc9ff48b9e8f48aca79fbecd089d5418"

[etherscan]
arbitrum = { key = "${}"}

# See more config options https://github.com/foundry-rs/foundry/tree/master/config